
server:
  port: 8085

app:
  urls:
    databasePort: "9092"
    client: "http://localhost:3000"
    camundaBaseUrl: "http://localhost:9090/engine-rest"
    startProcess: "/process-definition/key/document-processing-engine-process/start"
    getUnassignTask: "/task"
    claimTask: "/task/%s/claim"
    unclaimTask: "/task/%s/unclaim"
    taskCount: "/history/task/count?taskAssignee=admin"
    completeTask: "/task/%s/complete"
  
spring:
  application:
    name: DocumentProcessingApplication
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

