
camunda.bpm:
  admin-user:
    id: admin
    password: admin
  filter:
    create: All tasks

server:
  port: 9090



#camunda:
#  bpm:
#    database:
#      schema-update: 'true'
#      schema-name: camunda
#      table-prefix: camunda.



spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console